"""
Gotong Royong Accounting — High-Water Mark performance fee billing.

The HWM architecture ensures users are only charged on net new profits
generated by Vilona-tagged trades, never on recovery from drawdowns.

Key invariants:
  - Fee = 0 if current equity ≤ previous HWM (drawdown recovery is free)
  - Fee = 20% × (new equity − old HWM) when profit breaks the watermark
  - Only Vilona-tagged trades count (magic_number on MT5, clientOrderId prefix on CCXT)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path
from typing import Any

from tradebot.config import settings

LOG = logging.getLogger(__name__)

WIB = timezone(timedelta(hours=7))

# Precision: all monetary values use Decimal for exact float-free math
_QUANT = Decimal("0.01")


# ═══════════════════════════════════════════════════════════════════
#  DATA TRANSFER OBJECTS
# ═══════════════════════════════════════════════════════════════════


@dataclass
class BillingCycle:
    """Result of a single billing period for one user."""

    chat_id: str
    platform: str
    period_start: str
    period_end: str
    hwm_baseline: float
    bot_pnl: float
    hwm_new: float
    fee_amount: float
    payment_status: str = "unpaid"


@dataclass
class TradeRecord:
    """A single closed trade for P&L calculation."""

    order_id: str
    symbol: str
    side: str  # buy / sell
    entry_price: float
    exit_price: float
    amount: float
    fee: float = 0.0
    realized_pnl: float = 0.0  # broker-side realized P&L
    closed_at: str = ""
    identifier: str = ""  # magic number or clientOrderId for tag filtering


# ═══════════════════════════════════════════════════════════════════
#  ACCOUNTING SERVICE
# ═══════════════════════════════════════════════════════════════════


class AccountingService:
    """High-Water Mark billing engine for the Gotong Royong framework.

    Usage:
        svc = AccountingService(db_path="data/tradebot.db")
        cycle = await svc.generate_billing_cycle(
            chat_id="12345",
            platform="ccxt",
            trades=trades_from_broker,
        )
    """

    def __init__(
        self,
        db_path: str = "",
        fee_rate: float | None = None,
        payment_url: str = "",
    ) -> None:
        self._db_path = Path(db_path) if db_path else Path(settings.DATA_DIR) / "tradebot.db"
        self.fee_rate = fee_rate if fee_rate is not None else settings.GOTONG_ROYONG_FEE_RATE
        self.payment_url = payment_url or settings.GOTONG_ROYONG_PAYMENT_URL or ""
        self._ensure_schema()

    # ── Schema ────────────────────────────────────────────────────

    def _ensure_schema(self) -> None:
        """Create the ledger table if it does not exist."""
        import sqlite3

        sql_path = (
            Path(__file__).resolve().parent.parent
            / "db" / "migrations" / "001_create_ledger.sql"
        )
        conn = sqlite3.connect(str(self._db_path))
        try:
            if sql_path.exists():
                conn.executescript(sql_path.read_text())
            else:
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS vilona_ledger (
                        id              INTEGER PRIMARY KEY AUTOINCREMENT,
                        chat_id         TEXT NOT NULL,
                        platform        TEXT NOT NULL DEFAULT 'ccxt',
                        period_start    TEXT NOT NULL,
                        period_end      TEXT NOT NULL,
                        hwm_baseline    REAL NOT NULL DEFAULT 0.0,
                        bot_pnl         REAL NOT NULL DEFAULT 0.0,
                        hwm_new         REAL NOT NULL DEFAULT 0.0,
                        fee_amount      REAL NOT NULL DEFAULT 0.0,
                        payment_status  TEXT NOT NULL DEFAULT 'unpaid',
                        generated_at    TEXT NOT NULL,
                        paid_at         TEXT DEFAULT NULL,
                        UNIQUE(chat_id, platform, period_start)
                    )
                """)
                conn.execute(
                    "CREATE INDEX IF NOT EXISTS idx_ledger_chat "
                    "ON vilona_ledger(chat_id, platform)"
                )
                conn.execute(
                    "CREATE INDEX IF NOT EXISTS idx_ledger_status "
                    "ON vilona_ledger(payment_status)"
                )
            conn.commit()
        finally:
            conn.close()

    # ── Trade filtering ───────────────────────────────────────────

    def filter_vilona_trades(
        self,
        trades: list[TradeRecord],
        platform: str,
    ) -> list[TradeRecord]:
        """Return only trades tagged with the Vilona identifier.

        MT5:   matches magic_number 7771041
        CCXT:  matches clientOrderId prefix "vilona_ai_"
        """
        if platform == "mt5":
            magic_str = str(settings.GOTONG_ROYONG_MAGIC_NUMBER)
            return [
                t for t in trades
                if magic_str in (t.identifier or "")
            ]
        elif platform == "ccxt":
            prefix = settings.GOTONG_ROYONG_CCXT_PREFIX
            return [
                t for t in trades
                if (t.identifier or "").startswith(prefix)
            ]
        return trades

    # ── P&L calculation ───────────────────────────────────────────

    def calculate_weekly_pnl(
        self,
        trades: list[TradeRecord],
        platform: str,
    ) -> float:
        """Sum realized P&L from Vilona-tagged trades over the given period.

        Uses Decimal arithmetic to avoid floating-point drift.
        """
        vilona_trades = self.filter_vilona_trades(trades, platform)
        if not vilona_trades:
            return 0.0

        total = Decimal("0")
        for t in vilona_trades:
            if t.realized_pnl != 0.0:
                total += Decimal(str(t.realized_pnl))
            else:
                # Fallback: compute from entry/exit/amount
                entry_d = Decimal(str(t.entry_price))
                exit_d = Decimal(str(t.exit_price))
                amount_d = Decimal(str(t.amount))
                fee_d = Decimal(str(t.fee))

                if t.side.lower() == "buy":
                    pnl = (exit_d - entry_d) * amount_d - fee_d
                else:
                    pnl = (entry_d - exit_d) * amount_d - fee_d

                total += pnl

        return float(total.quantize(_QUANT, rounding=ROUND_HALF_UP))

    # ── HWM billing ───────────────────────────────────────────────

    def compute_fee(
        self,
        hwm_baseline: float,
        running_equity_before: float,
        bot_pnl: float,
    ) -> tuple[float, float]:
        """Calculate fee and new HWM.

        Returns:
            (fee_amount, hwm_new)

        The fee is only charged on the portion of new equity that exceeds the
        previous high-water mark. Running equity tracks the cumulative P&L
        across all periods, not just this period's gain.

        Examples:
            HWM=1000, equity=1000, P&L=+200 → fee=40.00,  HWM=1200
            HWM=1000, equity=1000, P&L=−50  → fee=0.00,   HWM=1000
            HWM=1500, equity=1300, P&L=+100 → fee=0.00,   HWM=1500 (recovery, still below peak)
            HWM=1500, equity=1300, P&L=+300 → fee=20.00,  HWM=1600 (only profit above HWM charged)
        """
        baseline_d = Decimal(str(hwm_baseline))
        equity_d = Decimal(str(running_equity_before))
        pnl_d = Decimal(str(bot_pnl))
        rate_d = Decimal(str(self.fee_rate))

        new_equity = equity_d + pnl_d
        hwm_new = max(baseline_d, new_equity)

        if new_equity <= baseline_d:
            return 0.0, float(hwm_new)

        profit_above_hwm = new_equity - baseline_d
        fee = (profit_above_hwm * rate_d).quantize(_QUANT, rounding=ROUND_HALF_UP)

        return float(fee), float(hwm_new)

    # ── Billing cycle orchestration ───────────────────────────────

    async def generate_billing_cycle(
        self,
        chat_id: str,
        platform: str,
        trades: list[TradeRecord],
        period_start: str = "",
        period_end: str = "",
    ) -> BillingCycle:
        """Run a full billing cycle: fetch HWM → calculate PnL → compute fee → store.

        Args:
            chat_id: Telegram chat ID
            platform: Broker platform (ccxt, mt5)
            trades: Closed trades for the period (pre-filtered by caller)
            period_start: ISO date (default: last Monday)
            period_end: ISO date (default: last Sunday)

        Returns:
            BillingCycle with all computed fields.
        """
        import sqlite3
        from datetime import datetime as dt

        now = dt.now(WIB)

        # Default to the previous Monday–Sunday window
        if not period_start:
            days_since_monday = now.weekday()
            last_monday = now - timedelta(days=days_since_monday + 7)
            period_start = last_monday.strftime("%Y-%m-%d")
        if not period_end:
            period_end_dt = dt.fromisoformat(period_start) + timedelta(days=6)
            period_end = period_end_dt.strftime("%Y-%m-%d")

        # Fetch last HWM and running equity from the ledger
        hwm_baseline = self._get_last_hwm(chat_id, platform)
        running_equity = self._get_running_equity(chat_id, platform)

        # Calculate P&L for Vilona-tagged trades only
        bot_pnl = self.calculate_weekly_pnl(trades, platform)

        # Compute fee and new HWM
        fee_amount, hwm_new = self.compute_fee(hwm_baseline, running_equity, bot_pnl)

        # Insert ledger record
        conn = sqlite3.connect(str(self._db_path))
        try:
            conn.execute(
                """INSERT OR REPLACE INTO vilona_ledger
                   (chat_id, platform, period_start, period_end,
                    hwm_baseline, bot_pnl, hwm_new, fee_amount,
                    payment_status, generated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'unpaid', ?)""",
                (
                    chat_id,
                    platform,
                    period_start,
                    period_end,
                    hwm_baseline,
                    bot_pnl,
                    hwm_new,
                    fee_amount,
                    now.isoformat(),
                ),
            )
            conn.commit()
        finally:
            conn.close()

        LOG.info(
            "Billing cycle: uid=%s platform=%s period=%s→%s "
            "hwm=%.2f pnl=%.2f new_hwm=%.2f fee=%.2f",
            chat_id, platform, period_start, period_end,
            hwm_baseline, bot_pnl, hwm_new, fee_amount,
        )

        return BillingCycle(
            chat_id=chat_id,
            platform=platform,
            period_start=period_start,
            period_end=period_end,
            hwm_baseline=hwm_baseline,
            bot_pnl=bot_pnl,
            hwm_new=hwm_new,
            fee_amount=fee_amount,
            payment_status="unpaid",
        )

    # ── Ledger queries ────────────────────────────────────────────

    def _get_last_hwm(self, chat_id: str, platform: str) -> float:
        """Fetch the most recent HWM for a user+platform pair.

        Returns 0.0 if no prior ledger entry exists (new user).
        """
        import sqlite3

        conn = sqlite3.connect(str(self._db_path))
        try:
            row = conn.execute(
                """SELECT hwm_new FROM vilona_ledger
                   WHERE chat_id = ? AND platform = ?
                   ORDER BY period_end DESC LIMIT 1""",
                (chat_id, platform),
            ).fetchone()
            return float(row[0]) if row else 0.0
        finally:
            conn.close()

    def _get_running_equity(self, chat_id: str, platform: str) -> float:
        """Sum all prior bot_pnl to compute current running equity.

        This is the cumulative P&L across ALL completed periods.
        Used to determine if a positive period actually breaks the HWM
        or is just recovering from prior drawdowns.
        """
        import sqlite3

        conn = sqlite3.connect(str(self._db_path))
        try:
            row = conn.execute(
                """SELECT COALESCE(SUM(bot_pnl), 0.0) FROM vilona_ledger
                   WHERE chat_id = ? AND platform = ?""",
                (chat_id, platform),
            ).fetchone()
            return float(row[0]) if row else 0.0
        finally:
            conn.close()

    def get_ledger(
        self,
        chat_id: str,
        platform: str = "",
        status: str = "",
    ) -> list[dict[str, Any]]:
        """Query billing history for a user."""
        import sqlite3

        conn = sqlite3.connect(str(self._db_path))
        conn.row_factory = sqlite3.Row
        try:
            where = ["chat_id = ?"]
            params: list[str] = [chat_id]
            if platform:
                where.append("platform = ?")
                params.append(platform)
            if status:
                where.append("payment_status = ?")
                params.append(status)

            sql = (
                "SELECT * FROM vilona_ledger WHERE "
                + " AND ".join(where)
                + " ORDER BY period_end DESC"
            )
            rows = conn.execute(sql, tuple(params)).fetchall()
            return [dict(r) for r in rows]
        finally:
            conn.close()

    def get_unpaid_fees(self, chat_id: str = "") -> list[dict[str, Any]]:
        """Get all unpaid billing cycles (optionally filtered by user)."""
        import sqlite3

        conn = sqlite3.connect(str(self._db_path))
        conn.row_factory = sqlite3.Row
        try:
            if chat_id:
                rows = conn.execute(
                    "SELECT * FROM vilona_ledger WHERE chat_id = ? AND payment_status = 'unpaid' "
                    "ORDER BY period_end DESC",
                    (chat_id,),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT * FROM vilona_ledger WHERE payment_status = 'unpaid' "
                    "ORDER BY period_end DESC"
                ).fetchall()
            return [dict(r) for r in rows]
        finally:
            conn.close()

    def mark_paid(self, ledger_id: int) -> None:
        """Mark a billing cycle as paid."""
        import sqlite3
        from datetime import datetime as dt

        conn = sqlite3.connect(str(self._db_path))
        try:
            conn.execute(
                "UPDATE vilona_ledger SET payment_status = 'paid', paid_at = ? WHERE id = ?",
                (dt.now(WIB).isoformat(), ledger_id),
            )
            conn.commit()
        finally:
            conn.close()
